### ISSUE TITLE
turn right and left not working on android

### ISSUE THREAD

**Issue by brahimjid** [osamaqarem/liveness-detection-react-native#2] opened 2022-12-27 10:46 UTC

**Comment by vinhhoangdo** [comment] 2023-06-01 08:46
You can follow this link and try converting yaw and roll.!!!
Work for me: ` angle > 180 ? angle - 360 : angle`
https://stackoverflow.com/questions/67555851/expo-face-detector-angle

**Comment by osamaqarem** [comment] 2023-06-08 06:42
Duplicate of https://github.com/osamaqarem/liveness-detection-react-native/issues/1

**Closed as not planned by osamaqarem** 2023-06-08 06:42 UTC
